[package]
name = "telemetry"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
axum.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

prometheus = "0.13"
once_cell = "1.21"

opentelemetry = "0.32"
opentelemetry_sdk = { version = "0.32", features = ["rt-tokio", "trace"] }
opentelemetry-otlp = { version = "0.32", features = ["grpc-tonic", "trace"] }
tracing-opentelemetry = "0.33"