[package]
name = "health"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"

tokio = { version = "1", features = ["rt", "rt-multi-thread"] }

async-trait = "0.1"

serde = { version = "1", features = ["derive"] }

sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-rustls"] }

rdkafka = "0.36"